apiVersion: v1
entries:
  atlantis:
  - apiVersion: v1
    appVersion: v0.4.11
    created: 2018-11-26T15:32:40.123559983-07:00
    description: A Helm chart for Atlantis https://www.runatlantis.io
    digest: 9ec8e1f12c0e0705bb1cba180c671ed3e7a94c82a83038e3275b204ea3e7f0f8
    home: https://www.runatlantis.io
    icon: https://www.runatlantis.io/hero.png
    keywords:
    - terraform
    maintainers:
    - name: jkodroff
    - name: callmeradical
    - name: jeff-knurek
    - name: lkysow
    name: atlantis
    sources:
    - https://github.com/runatlantis/atlantis
    urls:
    - atlantis-0.1.0.tgz
    version: 0.1.0
generated: 2018-11-26T15:32:40.123042965-07:00
